import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
  renderToBuffer,
} from "@react-pdf/renderer";
import React from "react";

import type { StrategyPack } from "@/lib/domain/strategyPack";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: "Helvetica", color: "#18181b" },
  h1: { fontSize: 20, marginBottom: 2 },
  sub: { fontSize: 10, color: "#71717a", marginBottom: 16 },
  h2: { fontSize: 13, marginTop: 16, marginBottom: 6, color: "#27272a" },
  row: { flexDirection: "row", marginBottom: 2 },
  key: { width: 110, color: "#71717a" },
  val: { flex: 1 },
  li: { marginBottom: 3 },
  trow: { flexDirection: "row", borderBottom: "1 solid #e4e4e7", paddingVertical: 3 },
  c1: { flex: 3 },
  c2: { flex: 1, textAlign: "right" },
  c3: { flex: 1, textAlign: "right" },
  body: { lineHeight: 1.5 },
});

function Doc({ pack }: { pack: StrategyPack }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.h1}>{pack.title}</Text>
        <Text style={styles.sub}>
          {pack.tenantName} · {pack.orgTier} · {pack.archetype} · {pack.maturity} ·{" "}
          {pack.status}
        </Text>

        <View style={styles.row}>
          <Text style={styles.key}>Taxonomy</Text>
          <Text style={styles.val}>{pack.taxonomy || "—"}</Text>
        </View>
        {pack.objective ? (
          <View style={styles.row}>
            <Text style={styles.key}>Objective</Text>
            <Text style={styles.val}>{pack.objective}</Text>
          </View>
        ) : null}
        <View style={styles.row}>
          <Text style={styles.key}>Frameworks</Text>
          <Text style={styles.val}>{pack.frameworks.join(", ")}</Text>
        </View>

        {pack.aiSummary ? (
          <View>
            <Text style={styles.h2}>Executive summary</Text>
            <Text style={styles.body}>{pack.aiSummary.output}</Text>
          </View>
        ) : null}

        {pack.positioning ? (
          <View>
            <Text style={styles.h2}>Positioning</Text>
            <Text>
              {pack.positioning.quadrant} (supply risk {pack.positioning.supplyRisk}, business
              impact {pack.positioning.businessImpact})
            </Text>
            <Text style={{ color: "#71717a" }}>{pack.positioning.posture}</Text>
            {pack.positioning.rationale ? <Text>{pack.positioning.rationale}</Text> : null}
          </View>
        ) : null}

        <Text style={styles.h2}>Options</Text>
        <View style={styles.trow}>
          <Text style={styles.c1}>Option</Text>
          <Text style={styles.c2}>Score</Text>
          <Text style={styles.c3}>NPV</Text>
        </View>
        {pack.options.map((o, i) => (
          <View style={styles.trow} key={i}>
            <Text style={styles.c1}>
              {o.label}
              {o.isBaseline ? " (baseline)" : ""}
              {o.isSelected ? " ★" : ""}
            </Text>
            <Text style={styles.c2}>{o.score}</Text>
            <Text style={styles.c3}>{o.npv}</Text>
          </View>
        ))}

        <Text style={styles.h2}>Evidence ({pack.evidence.length})</Text>
        {pack.evidence.map((e, i) => (
          <Text style={styles.li} key={i}>
            • {e.claim} ({e.sourceType}, {e.confidence.toLowerCase()}, {e.collectedAt})
          </Text>
        ))}

        <Text style={{ ...styles.sub, marginTop: 24 }}>
          Generated by StratIQ · {pack.generatedAt}
        </Text>
      </Page>
    </Document>
  );
}

export async function toPdfBuffer(pack: StrategyPack): Promise<Buffer> {
  return renderToBuffer(<Doc pack={pack} />);
}
